refactor: bring in code from virtool-cli

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,6 +18,14 @@ jobs:
   test:
     runs-on: ubuntu-22.04
     steps:
+      - name: Check NCBI secrets
+        env:
+          secret_email: ${{ secrets.NCBI_EMAIL }}
+          secret_api_key: ${{ secrets.NCBI_API_KEY }}
+        if: ${{ env.secret_email == '' || env.secret_api_key == '' }}
+        run: |
+          echo "NCBI authentication secret missing. Exiting."
+          exit 1
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup Python
@@ -27,25 +35,13 @@ jobs:
       - name: Install Poetry
         uses: snok/install-poetry@v1
         with:
+          installer-parallel: true
           virtualenvs-create: true
           virtualenvs-in-project: true
-          installer-parallel: true
       - name: Install packages
         run: poetry install
-      - name: Run unit tests
-        run: poetry run pytest -m "not ncbi" --disable-socket --allow-unix-socket
-      - name: Check if NCBI auth is present, fail out if missing
-        env:
-          super_secret: ${{ secrets.NCBI_API_KEY }}
-        if: ${{ env.super_secret == '' }}
-        run: |
-          echo "NCBI authentication not provided. Failing out."
-          exit 1
-      - name: Run NCBI-dependent tests
-        run: poetry run pytest -m "ncbi"
-        env:
-          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
-          NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}
+      - name: Test
+        run: poetry run pytest
   release:
     if: github.event_name == 'push'
     needs:
